
services:
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      #MYSQL_DATABASE: pwtriptales_db
      #MYSQL_USER: root
      #MYSQL_PASSWORD: rootroot
    expose:
      - "3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  web:
    image: python
    ports:
      - "8013:8000"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: >
      sh -c "sleep 5 &&
             pip install --no-cache-dir -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db