# Generated by Django 5.2.1 on 2025-05-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_badge', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gruppo', models.CharField(max_length=100)),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('codice_accesso', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('testo', models.TextField(blank=True)),
                ('immagine_path', models.ImageField(upload_to='foto_post/')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('testo_OCR', models.TextField(blank=True, null=True)),
                ('testo_tradotto', models.TextField(blank=True, null=True)),
                ('tags_oggetti', models.CharField(blank=True, max_length=255, null=True)),
                ('didascalia_automatica', models.TextField(blank=True, null=True)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gruppo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utente')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_like', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
                ('utente_che_ha_messo_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utente')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assegnazione', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.badge')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utente')),
            ],
        ),
        migrations.CreateModel(
            name='UtenteGruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(default='partecipante', max_length=50)),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gruppo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utente')),
            ],
        ),
    ]
